// Curated, unambiguous geography questions. The answer index refers to the original options.
const rows=[
['Capitals','What is the capital of Japan?',['Tokyo','Kyoto','Osaka','Nagoya'],0,'Tokyo is Japan’s capital. Kyoto served as the imperial capital for over a thousand years.'],
['Capitals','What is the capital of Australia?',['Sydney','Canberra','Melbourne','Perth'],1,'Canberra was selected as the capital as a compromise between Sydney and Melbourne.'],
['Capitals','What is the capital of Canada?',['Toronto','Vancouver','Ottawa','Montreal'],2,'Ottawa is on the Ottawa River in the province of Ontario.'],
['Capitals','Which city is the capital of Brazil?',['Rio de Janeiro','São Paulo','Brasília','Salvador'],2,'Brasília became the capital in 1960, replacing Rio de Janeiro.'],
['Capitals','What is the capital of Egypt?',['Alexandria','Cairo','Luxor','Aswan'],1,'Cairo lies near the head of the Nile Delta.'],
['Capitals','What is the capital of New Zealand?',['Auckland','Christchurch','Wellington','Hamilton'],2,'Wellington is near the southern tip of New Zealand’s North Island.'],
['Capitals','What is the capital of Thailand?',['Bangkok','Hanoi','Phnom Penh','Vientiane'],0,'Bangkok is Thailand’s capital and lies on the Chao Phraya River.'],
['Capitals','What is the capital of Kenya?',['Mombasa','Nairobi','Kisumu','Nakuru'],1,'Nairobi is Kenya’s capital, situated in the country’s highlands.'],
['Capitals','What is the capital of Italy?',['Milan','Venice','Rome','Florence'],2,'Rome is Italy’s capital. Vatican City is an independent state surrounded by Rome.'],
['Capitals','What is the capital of Argentina?',['Lima','Santiago','Montevideo','Buenos Aires'],3,'Buenos Aires is situated on the western shore of the Río de la Plata.'],
['World geography','Which is the largest continent by land area?',['Africa','Asia','Europe','Antarctica'],1,'Asia is the largest continent by both land area and population.'],
['World geography','Which ocean is the largest?',['Atlantic Ocean','Indian Ocean','Pacific Ocean','Arctic Ocean'],2,'The Pacific Ocean covers more area than any other ocean.'],
['World geography','Which imaginary line divides Earth into Northern and Southern Hemispheres?',['Prime Meridian','Equator','Tropic of Cancer','Arctic Circle'],1,'The Equator is the line of zero degrees latitude.'],
['World geography','On which continent is the Sahara Desert?',['Asia','Africa','Australia','South America'],1,'The Sahara stretches across much of northern Africa.'],
['World geography','Which country has the greatest land area?',['Canada','China','Russia','Brazil'],2,'Russia extends across eastern Europe and northern Asia.'],
['World geography','Which continent has no permanent native human population?',['Europe','Antarctica','Australia','Asia'],1,'Antarctica hosts research stations, but has no permanent native human population.'],
['World geography','The Andes mountain range runs along which continent?',['South America','North America','Europe','Africa'],0,'The Andes run along the western edge of South America.'],
['World geography','Which sea lies between Europe and northern Africa?',['Red Sea','Caribbean Sea','Mediterranean Sea','Baltic Sea'],2,'The Mediterranean Sea connects to the Atlantic through the Strait of Gibraltar.'],
['World geography','Which country is shaped like a boot on a map?',['Greece','Italy','Portugal','Norway'],1,'Italy’s peninsula extends into the Mediterranean Sea.'],
['World geography','Which line is designated zero degrees longitude?',['Equator','Tropic of Capricorn','Prime Meridian','Antarctic Circle'],2,'The prime meridian at Greenwich is the reference for zero degrees longitude.'],
['Philippines','What is the capital of the Philippines?',['Quezon City','Manila','Cebu City','Davao City'],1,'Manila is the national capital and is part of Metro Manila.'],
['Philippines','Which is the largest island in the Philippines?',['Mindanao','Samar','Luzon','Palawan'],2,'Luzon is the country’s largest island and contains Metro Manila.'],
['Philippines','Which Philippine province is famous for the Chocolate Hills?',['Bohol','Cebu','Albay','Aklan'],0,'The Chocolate Hills of Bohol become brown in the dry season.'],
['Philippines','Mayon Volcano is located in which province?',['Batangas','Albay','Laguna','Zambales'],1,'Mayon is in Albay in the Bicol Region.'],
['Philippines','Which is the highest mountain in the Philippines?',['Mount Pulag','Mount Apo','Mount Banahaw','Mount Makiling'],1,'Mount Apo stands on Mindanao and is the country’s highest mountain.'],
['Philippines','Which of these is one of the three major island groups of the Philippines?',['Palawan','Batanes','Visayas','Bohol'],2,'The three major island groups are Luzon, Visayas, and Mindanao.'],
['Philippines','The Puerto Princesa Underground River is on which island?',['Panay','Palawan','Negros','Leyte'],1,'The underground river is located on Palawan, near Puerto Princesa.'],
['Philippines','Boracay belongs to which Philippine province?',['Aklan','Antique','Iloilo','Capiz'],0,'Boracay is part of the municipality of Malay in Aklan.'],
['Philippines','Which ocean lies east of the Philippines?',['Indian Ocean','Atlantic Ocean','Pacific Ocean','Arctic Ocean'],2,'The Philippine Sea is part of the western Pacific Ocean.'],
['Philippines','Which city is known as the Summer Capital of the Philippines?',['Tagaytay','Baguio','Vigan','Bacolod'],1,'Baguio’s high elevation in the Cordillera mountains gives it a cooler climate.'],
['Land & water','Which is the largest hot desert in the world?',['Gobi','Kalahari','Sahara','Arabian Desert'],2,'The Sahara is the largest hot desert. Antarctica is larger, but is a cold desert.'],
['Land & water','Mount Everest belongs to which mountain range?',['Alps','Andes','Himalayas','Rockies'],2,'The Himalayas formed through the collision of the Indian and Eurasian tectonic plates.'],
['Land & water','What is a piece of land surrounded by water on all sides called?',['Peninsula','Isthmus','Island','Plateau'],2,'An island is surrounded by water; a peninsula remains connected to a larger landmass.'],
['Land & water','What is a narrow strip of land connecting two larger land areas called?',['Strait','Isthmus','Delta','Archipelago'],1,'An isthmus connects two land areas, such as the Isthmus of Panama.'],
['Land & water','What is a group of islands called?',['Archipelago','Peninsula','Estuary','Basin'],0,'An archipelago is a group or chain of islands.'],
['Land & water','Which river flows through Egypt?',['Amazon','Danube','Nile','Mekong'],2,'The Nile flows north through Egypt and empties into the Mediterranean Sea.'],
['Land & water','Which ocean lies between Africa and Australia?',['Pacific Ocean','Atlantic Ocean','Indian Ocean','Arctic Ocean'],2,'The Indian Ocean is bordered by Africa to the west and Australia to the east.'],
['Land & water','Which is the deepest known oceanic trench?',['Java Trench','Mariana Trench','Peru–Chile Trench','Puerto Rico Trench'],1,'The Mariana Trench in the western Pacific contains Challenger Deep.'],
['Land & water','Which lake is the deepest in the world?',['Lake Victoria','Lake Superior','Lake Baikal','Lake Titicaca'],2,'Lake Baikal in Siberia is the world’s deepest lake.'],
['Land & water','Which waterfall lies on the border of Zambia and Zimbabwe?',['Niagara Falls','Angel Falls','Victoria Falls','Iguazu Falls'],2,'Victoria Falls lies on the Zambezi River between Zambia and Zimbabwe.'],
['Maps & navigation','What does a map legend explain?',['The map’s age','The map’s symbols','The weather','The mapmaker’s route'],1,'A legend explains what the symbols and colors on a map represent.','easy'],
['Maps & navigation','If north is at the top of a map, which direction is to the right?',['West','South','East','North'],2,'On a north-up map, east is to the right.','easy'],
['Maps & navigation','What does a compass rose show on a map?',['Population','Directions','Elevation','Rainfall'],1,'A compass rose marks directions such as north, south, east, and west.','easy'],
['Maps & navigation','What does a map scale compare?',['Map distance with real distance','Rainfall with temperature','Land height with sea depth','Population with area'],0,'A map scale relates a distance on the map to a distance on the ground.','medium'],
['Maps & navigation','Which coordinate tells how far north or south a place is from the Equator?',['Longitude','Altitude','Latitude','Bearing'],2,'Latitude measures angular distance north or south of the Equator.','medium'],
['Maps & navigation','Which coordinate tells how far east or west a place is from the prime meridian?',['Latitude','Longitude','Elevation','Scale'],1,'Longitude measures angular distance east or west of the prime meridian.','medium'],
['Maps & navigation','On a topographic map, a contour line connects places with the same what?',['Temperature','Elevation','Population','Rainfall'],1,'Every point on a contour line has the same elevation.','medium'],
['Maps & navigation','What do tightly spaced contour lines usually show?',['A steep slope','A wide plain','A river mouth','A city boundary'],0,'Nearby contour lines mean elevation changes quickly over a short distance.','hard'],
['Maps & navigation','At a map scale of 1:100,000, one centimeter on the map represents how far on the ground?',['One meter','One hundred meters','One kilometer','Ten kilometers'],2,'100,000 centimeters equal 1,000 meters, or one kilometer.','hard'],
['Maps & navigation','If you travel from 20° south latitude to 10° south latitude, which direction are you moving?',['East','West','South','North'],3,'Ten degrees south is closer to the Equator than twenty degrees south, so the travel is northward.','hard'],
['Climate & weather','Which instrument measures air temperature?',['Thermometer','Rain gauge','Compass','Barometer'],0,'A thermometer measures temperature.','easy'],
['Climate & weather','Which instrument measures the amount of rain that has fallen?',['Anemometer','Thermometer','Rain gauge','Compass'],2,'A rain gauge collects precipitation so its amount can be measured.','easy'],
['Climate & weather','What is water that falls from clouds as rain, snow, or hail called?',['Evaporation','Precipitation','Humidity','Condensation'],1,'Precipitation includes rain, snow, sleet, and hail.','easy'],
['Climate & weather','What word describes an area’s usual weather patterns over many years?',['Forecast','Season','Climate','Storm'],2,'Climate describes long-term patterns; weather describes current conditions.','medium'],
['Climate & weather','A monsoon is primarily a seasonal change in what?',['Ocean depth','Wind patterns','Latitude','Day length'],1,'Monsoon winds reverse or shift seasonally and can bring wet and dry seasons.','medium'],
['Climate & weather','What happens during condensation?',['Liquid water becomes vapor','Water vapor becomes liquid droplets','Ice becomes vapor directly','Rainwater enters the ground'],1,'Condensation changes water vapor in the air into liquid droplets.','medium'],
['Climate & weather','As moist air rises over a mountain, which side usually receives more rain?',['Leeward side','Windward side','Northern side','Lower side'],1,'Air rising on the windward side cools, allowing moisture to condense and fall.','medium'],
['Climate & weather','Why do nearby seas often make coastal temperatures less extreme?',['Water heats and cools more slowly than land','Salt water blocks sunlight','The coast is always higher','Ocean currents stop all wind'],0,'Water changes temperature more slowly than land, moderating nearby air.','hard'],
['Climate & weather','In June, which hemisphere is tilted toward the Sun?',['Southern Hemisphere','Eastern Hemisphere','Western Hemisphere','Northern Hemisphere'],3,'Around the June solstice, the Northern Hemisphere tilts toward the Sun.','hard'],
['Climate & weather','What is the main reason Earth has seasons?',['Its changing distance from the Sun','Its tilted axis as it orbits the Sun','The Moon blocking sunlight','The speed of Earth’s rotation'],1,'Earth’s axial tilt changes the angle and length of sunlight through the year.','hard'],
['Natural landmarks','Which river has carved much of the Grand Canyon?',['Colorado River','Nile River','Amazon River','Danube River'],0,'The Colorado River and its tributaries have carved the Grand Canyon over millions of years.','easy'],
['Natural landmarks','Niagara Falls lies on the border of which two countries?',['United States and Mexico','United States and Canada','Canada and Greenland','Canada and Iceland'],1,'Niagara Falls straddles the border between the United States and Canada.','easy'],
['Natural landmarks','What is the bowl-shaped hollow around the opening of many volcanoes called?',['Delta','Crater','Fjord','Atoll'],1,'A volcanic crater is a depression around a vent or opening.','easy'],
['Natural landmarks','What is a curved lake left behind when a river bend is cut off?',['Lagoon','Reservoir','Oxbow lake','Tarn'],2,'An oxbow lake forms when a river takes a shorter route and leaves a former meander isolated.','medium'],
['Natural landmarks','What process helps form many limestone caves by dissolving rock?',['Chemical weathering','Volcanic eruption','Glacial freezing','Wind deposition'],0,'Slightly acidic water slowly dissolves limestone, a form of chemical weathering.','medium'],
['Natural landmarks','What material builds up at some river mouths to form a delta?',['Lava','Sediment','Sea ice','Coral'],1,'Rivers can deposit sediment where they meet slower-moving water.','medium'],
['Natural landmarks','What natural force carved many U-shaped mountain valleys?',['Wind','Glaciers','Ocean tides','Earthquakes'],1,'Moving glaciers erode valley floors and sides, often leaving a U-shaped cross-section.','medium'],
['Natural landmarks','What is a ridge of rock and soil left by a glacier called?',['Moraine','Estuary','Aquifer','Mesa'],0,'A moraine is an accumulation of debris transported and deposited by a glacier.','hard'],
['Natural landmarks','What process most often creates a sea arch in a coastal cliff?',['Wave erosion','Volcanic ashfall','River flooding','Soil formation'],0,'Waves can erode weaknesses in a headland until a hole opens into an arch.','hard'],
['Natural landmarks','What kind of plate boundary can form a volcanic island arc?',['A subduction boundary','A transform boundary','A passive margin','A continental rift only'],0,'Subduction of one oceanic plate beneath another can generate a curved chain of volcanic islands.','hard'],
['Countries & cultures','Which language is primarily spoken in Brazil?',['Spanish','Portuguese','French','Italian'],1,'Portuguese is the official and most widely spoken language of Brazil.','easy'],
['Countries & cultures','In which country is the Taj Mahal?',['India','Nepal','Pakistan','Bangladesh'],0,'The Taj Mahal stands in Agra, India.','easy'],
['Countries & cultures','Māori are the Indigenous people of which country?',['Fiji','New Zealand','Samoa','Tonga'],1,'Māori are the Indigenous people of Aotearoa New Zealand.','easy'],
['Countries & cultures','Which civilization built Machu Picchu?',['Aztec','Maya','Inca','Roman'],2,'Machu Picchu was built by the Inca civilization in the Andes.','medium'],
['Countries & cultures','In which country is Angkor Wat?',['Thailand','Cambodia','Vietnam','Laos'],1,'Angkor Wat is part of the Angkor complex in Cambodia.','medium'],
['Countries & cultures','In which country is the ancient city of Petra?',['Jordan','Egypt','Turkey','Lebanon'],0,'Petra is an archaeological city in Jordan.','medium'],
['Countries & cultures','Which region of Spain is especially associated with flamenco?',['Galicia','Andalusia','Catalonia','Navarre'],1,'Andalusia is a heartland of flamenco, which also has roots elsewhere in Spain.','medium'],
['Countries & cultures','In which country is the Borobudur temple complex?',['Malaysia','Cambodia','Indonesia','Thailand'],2,'Borobudur is on the island of Java in Indonesia.','hard'],
['Countries & cultures','Which civilization built the city of Chichén Itzá?',['Inca','Maya','Olmec','Nabataean'],1,'Chichén Itzá is a major ancient Maya site on Mexico’s Yucatán Peninsula.','hard'],
['Countries & cultures','Rapa Nui, also called Easter Island, is part of which country?',['Peru','Chile','Ecuador','New Zealand'],1,'Rapa Nui is a Polynesian island that is part of Chile.','hard']
];
export const questions=rows.map(([category,prompt,options,answer,explanation,difficulty],i)=>({id:i+1,category,prompt,options,answer,explanation,...(difficulty?{difficulty}:{})}));
export const categories=[...new Set(questions.map(q=>q.category))];
