// Curated, unambiguous geography questions. The answer index refers to the original options.
const rows=[
['Capitals','What is the capital of Japan?',['Tokyo','Kyoto','Osaka','Nagoya'],0,'Tokyo is Japan’s capital. Kyoto served as the imperial capital for over a thousand years.'],
['Capitals','What is the capital of Australia?',['Sydney','Canberra','Melbourne','Perth'],1,'Canberra was selected as the capital as a compromise between Sydney and Melbourne.'],
['Capitals','What is the capital of Canada?',['Toronto','Vancouver','Ottawa','Montreal'],2,'Ottawa is on the Ottawa River in the province of Ontario.'],
['Capitals','Which city is the capital of Brazil?',['Rio de Janeiro','São Paulo','Brasília','Salvador'],2,'Brasília became the capital in 1960, replacing Rio de Janeiro.'],
['Capitals','What is the capital of Egypt?',['Alexandria','Cairo','Luxor','Aswan'],1,'Cairo lies near the head of the Nile Delta.'],
['Capitals','What is the capital of New Zealand?',['Auckland','Christchurch','Wellington','Hamilton'],2,'Wellington is near the southern tip of New Zealand’s North Island.'],
['Capitals','What is the capital of Thailand?',['Bangkok','Hanoi','Phnom Penh','Vientiane'],0,'Bangkok is Thailand’s capital and lies on the Chao Phraya River.'],
['Capitals','What is the capital of Kenya?',['Mombasa','Nairobi','Kisumu','Nakuru'],1,'Nairobi is Kenya’s capital, situated in the country’s highlands.'],
['Capitals','What is the capital of Italy?',['Milan','Venice','Rome','Florence'],2,'Rome is Italy’s capital. Vatican City is an independent state surrounded by Rome.'],
['Capitals','What is the capital of Argentina?',['Lima','Santiago','Montevideo','Buenos Aires'],3,'Buenos Aires is situated on the western shore of the Río de la Plata.'],
['World geography','Which is the largest continent by land area?',['Africa','Asia','Europe','Antarctica'],1,'Asia is the largest continent by both land area and population.'],
['World geography','Which ocean is the largest?',['Atlantic Ocean','Indian Ocean','Pacific Ocean','Arctic Ocean'],2,'The Pacific Ocean covers more area than any other ocean.'],
['World geography','Which imaginary line divides Earth into Northern and Southern Hemispheres?',['Prime Meridian','Equator','Tropic of Cancer','Arctic Circle'],1,'The Equator is the line of zero degrees latitude.'],
['World geography','On which continent is the Sahara Desert?',['Asia','Africa','Australia','South America'],1,'The Sahara stretches across much of northern Africa.'],
['World geography','Which country has the greatest land area?',['Canada','China','Russia','Brazil'],2,'Russia extends across eastern Europe and northern Asia.'],
['World geography','Which continent has no permanent native human population?',['Europe','Antarctica','Australia','Asia'],1,'Antarctica hosts research stations, but has no permanent native human population.'],
['World geography','The Andes mountain range runs along which continent?',['South America','North America','Europe','Africa'],0,'The Andes run along the western edge of South America.'],
['World geography','Which sea lies between Europe and northern Africa?',['Red Sea','Caribbean Sea','Mediterranean Sea','Baltic Sea'],2,'The Mediterranean Sea connects to the Atlantic through the Strait of Gibraltar.'],
['World geography','Which country is shaped like a boot on a map?',['Greece','Italy','Portugal','Norway'],1,'Italy’s peninsula extends into the Mediterranean Sea.'],
['World geography','Which line is designated zero degrees longitude?',['Equator','Tropic of Capricorn','Prime Meridian','Antarctic Circle'],2,'The prime meridian at Greenwich is the reference for zero degrees longitude.'],
['Philippines','What is the capital of the Philippines?',['Quezon City','Manila','Cebu City','Davao City'],1,'Manila is the national capital and is part of Metro Manila.'],
['Philippines','Which is the largest island in the Philippines?',['Mindanao','Samar','Luzon','Palawan'],2,'Luzon is the country’s largest island and contains Metro Manila.'],
['Philippines','Which Philippine province is famous for the Chocolate Hills?',['Bohol','Cebu','Albay','Aklan'],0,'The Chocolate Hills of Bohol become brown in the dry season.'],
['Philippines','Mayon Volcano is located in which province?',['Batangas','Albay','Laguna','Zambales'],1,'Mayon is in Albay in the Bicol Region.'],
['Philippines','Which is the highest mountain in the Philippines?',['Mount Pulag','Mount Apo','Mount Banahaw','Mount Makiling'],1,'Mount Apo stands on Mindanao and is the country’s highest mountain.'],
['Philippines','Which of these is one of the three major island groups of the Philippines?',['Palawan','Batanes','Visayas','Bohol'],2,'The three major island groups are Luzon, Visayas, and Mindanao.'],
['Philippines','The Puerto Princesa Underground River is on which island?',['Panay','Palawan','Negros','Leyte'],1,'The underground river is located on Palawan, near Puerto Princesa.'],
['Philippines','Boracay belongs to which Philippine province?',['Aklan','Antique','Iloilo','Capiz'],0,'Boracay is part of the municipality of Malay in Aklan.'],
['Philippines','Which ocean lies east of the Philippines?',['Indian Ocean','Atlantic Ocean','Pacific Ocean','Arctic Ocean'],2,'The Philippine Sea is part of the western Pacific Ocean.'],
['Philippines','Which city is known as the Summer Capital of the Philippines?',['Tagaytay','Baguio','Vigan','Bacolod'],1,'Baguio’s high elevation in the Cordillera mountains gives it a cooler climate.'],
['Land & water','Which is the largest hot desert in the world?',['Gobi','Kalahari','Sahara','Arabian Desert'],2,'The Sahara is the largest hot desert. Antarctica is larger, but is a cold desert.'],
['Land & water','Mount Everest belongs to which mountain range?',['Alps','Andes','Himalayas','Rockies'],2,'The Himalayas formed through the collision of the Indian and Eurasian tectonic plates.'],
['Land & water','What is a piece of land surrounded by water on all sides called?',['Peninsula','Isthmus','Island','Plateau'],2,'An island is surrounded by water; a peninsula remains connected to a larger landmass.'],
['Land & water','What is a narrow strip of land connecting two larger land areas called?',['Strait','Isthmus','Delta','Archipelago'],1,'An isthmus connects two land areas, such as the Isthmus of Panama.'],
['Land & water','What is a group of islands called?',['Archipelago','Peninsula','Estuary','Basin'],0,'An archipelago is a group or chain of islands.'],
['Land & water','Which river flows through Egypt?',['Amazon','Danube','Nile','Mekong'],2,'The Nile flows north through Egypt and empties into the Mediterranean Sea.'],
['Land & water','Which ocean lies between Africa and Australia?',['Pacific Ocean','Atlantic Ocean','Indian Ocean','Arctic Ocean'],2,'The Indian Ocean is bordered by Africa to the west and Australia to the east.'],
['Land & water','Which is the deepest known oceanic trench?',['Java Trench','Mariana Trench','Peru–Chile Trench','Puerto Rico Trench'],1,'The Mariana Trench in the western Pacific contains Challenger Deep.'],
['Land & water','Which lake is the deepest in the world?',['Lake Victoria','Lake Superior','Lake Baikal','Lake Titicaca'],2,'Lake Baikal in Siberia is the world’s deepest lake.'],
['Land & water','Which waterfall lies on the border of Zambia and Zimbabwe?',['Niagara Falls','Angel Falls','Victoria Falls','Iguazu Falls'],2,'Victoria Falls lies on the Zambezi River between Zambia and Zimbabwe.']
];
export const questions=rows.map(([category,prompt,options,answer,explanation],i)=>({id:i+1,category,prompt,options,answer,explanation}));
export const categories=[...new Set(questions.map(q=>q.category))];
