import test from 'node:test';
import assert from 'node:assert/strict';
import {testApp,registration} from './helpers.mjs';
import {migrate} from '../backend/database.mjs';
import {readFile} from 'node:fs/promises';
test('migrations are repeatable; production cookies are secure; maintenance is authenticated',async t=>{const app=await testApp();t.after(()=>app.db.close());await migrate(app.db);await migrate(app.db);app.config.production=true;app.config.origin='https://geovoice.example';app.config.cronSecret='test-only-maintenance-secret';await app.restart();const c=app.client('production-test');const r=await c.request('/auth/register','POST',registration('production_user'));assert.equal(r.status,201);assert.match(r.headers['set-cookie'],/^__Host-geovoice=/);assert.match(r.headers['set-cookie'],/; Secure/);assert.match(r.headers['set-cookie'],/; HttpOnly/);assert.match(r.headers['set-cookie'],/SameSite=Strict/);assert.ok(!r.headers['set-cookie'].includes('Domain='));assert.equal((await c.request('/maintenance')).status,401);assert.equal((await c.request('/maintenance','GET',undefined,{authorization:'Bearer test-only-maintenance-secret'})).status,200);});
test('Vercel config routes API separately and does not publish answer bank',async()=>{const config=JSON.parse(await readFile(new URL('../vercel.json',import.meta.url),'utf8'));assert.equal(config.outputDirectory,'dist');assert.equal(config.rewrites[0].source,'/api/:path*');assert.equal(config.functions['api/index.mjs'].maxDuration,60);await assert.rejects(()=>readFile(new URL('../dist/questions.js',import.meta.url)));});

test('upgrading the previous phone schema preserves accounts/history and expires old sessions only once',async t=>{
 const app=await testApp();t.after(()=>app.db.close());const c=app.client('upgrade');const registered=await c.request('/auth/register','POST',registration('upgrade_user'));const id=registered.data.user.id;
 const quiz=await c.request('/quizzes','POST',{category:'All',count:5});for(let index=0;index<5;index++)await c.request('/quizzes/'+quiz.data.id+'/answer','POST',{index,selected:0});
 await app.db.query(`ALTER TABLE users ADD COLUMN phone_cipher TEXT NOT NULL DEFAULT 'old-encrypted-phone'; ALTER TABLE users ADD COLUMN phone_hash TEXT NOT NULL DEFAULT 'old-phone-hash'; ALTER TABLE sessions DROP CONSTRAINT sessions_stage_check; ALTER TABLE sessions ADD CONSTRAINT sessions_stage_check CHECK(stage IN ('face','sms','full')); ALTER TABLE sessions ADD COLUMN otp_sid TEXT; ALTER TABLE sessions ADD COLUMN sms_sent BIGINT; ALTER TABLE sessions ADD COLUMN pending_password TEXT; ALTER TABLE sessions ADD COLUMN recovery_proof TEXT; ALTER TABLE sessions ADD COLUMN failures INTEGER NOT NULL DEFAULT 0; UPDATE sessions SET stage='sms'; UPDATE metadata SET value='1' WHERE key='schema_version';`);
 await migrate(app.db);await app.restart();assert.equal((await c.request('/session')).data.stage,'anonymous');
 const u=(await app.db.query('SELECT * FROM users WHERE id=$1',[id])).rows[0];assert.equal(u.username,'upgrade_user');assert.ok(!Object.hasOwn(u,'phone_cipher'));assert.ok(!Object.hasOwn(u,'phone_hash'));assert.equal((await app.db.query('SELECT * FROM quizzes WHERE user_id=$1 AND completed IS NOT NULL',[id])).rows.length,1);
 const {password,samples}=await import('./helpers.mjs');await c.request('/auth/login','POST',{username:'upgrade_user',password});assert.equal((await c.request('/auth/face','POST',{samples:samples(.1,2)})).data.stage,'full');
 await migrate(app.db);assert.equal((await c.request('/session')).data.stage,'full');assert.equal((await c.request('/history')).data.attempts.length,1);
});
